import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
// Imports reveal.js black theme
import 'reveal.js/dist/theme/black.css'

import Script from 'next/script'

import { ClientProviders } from '@/shared/config/client-providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <Script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'
        />

        <Script src='https://cdn.jsdelivr.net/npm/reveal.js-plugins@latest/customcontrols/plugin.js' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/reveal.js-plugins@latest/customcontrols/style.css'
        />
        <Script src='https://cdn.jsdelivr.net/npm/reveal.js-plugins@latest/chalkboard/plugin.js' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/reveal.js-plugins@latest/chalkboard/style.css'
        />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/reveal.js-plugins/menu/font-awesome/css/fontawesome.css'
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
